version: "3.9"

services:
  open-api:
    build:
      context: OpenApi/src/OpenApi
      dockerfile: Dockerfile
    environment:
      - Database__ConnectionString=Host=db;Port=5432;Database=elympics;Username=postgres;Password=secret
      - ASPNETCORE_URLS=http://+:80
      - UsersService__BasePath=http://users-service:8080
    container_name: open-api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 5241:80

  users-service:
    build:
      context: UsersService
      dockerfile: Dockerfile
    container_name: users-service
    restart: unless-stopped
    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=elympics
      - POSTGRES_DB=secret
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local    