apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: {{ .Values.usersService.service.type }}
  ports:
    - port: {{ .Values.usersService.service.port }}
      nodePort: {{ .Values.usersService.service.nodePort }}
  selector:
    app: users-service
